

server:
  port: 6001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        id: gateway-service


smartyang:
  gateway:
    # ���ض�̬·��
    dynamicRoute:
      enabled: true
      dataType: nacos